In [1]:
import tensorflow as tf
tf.__version__

'2.14.0'

In [2]:
import keras as k
k.__version__

'2.14.0'

In [ ]:
#Artificial Nueral Nw - you can have 2 to 3 hidden layers
# input layer
# hidden layr
# output later - we have to use activation functions on output nodes

# Linear
# nlinear
 #1. Sigmoid - 0,1 (S-curve)
 #2. softmax - similar to sigmoid (calc probabilities of the event over n different classes)
 #3. tanh function is -1 to 1 otherwise it is same as sigmoid
 #4. relu - converts anything that is less than zero to zero. range becomes 0 to infinity 

# In the hidden layer --> most of the time relu is used
# In output layer --> you can use sigmoid (in case of binary classification) or softmax (in case of multiple classification)

# ANN doesn't have restriction on dataset

# applications of ANN
  # Image preprocessing and character recognition
  # Forecasting
  # Credit rating
  # Fraud detection
  # Portfolio Management
    
# nb of hidden layers depend on problem statement

# Tensor = multi-dimensional data

# Tensorflow

## Basic Operations

#### Arithmatic operations

In [10]:
# Define tensor constants
a = tf.constant(5)
b = tf.constant(3)

In [11]:
# various tensor operations

add = tf.add(a,b)
sub = tf.subtract(a, b)
mul = tf.multiply(a, b)
div = tf.divide(a,b)



In [12]:
# Access tensors value
print('add = ', add.numpy())
print('sub = ', sub.numpy())
print('mul = ', mul.numpy())
print('div = ', div.numpy())

add =  8
sub =  2
mul =  15
div =  1.6666666666666667


In [13]:
add

<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [14]:
add.numpy()

8

### Matrix multiplication

In [16]:
matrix1 = tf.constant([[1,2],[3,4]])
matrix2 = tf.constant([[5,6],[7,8]])

product = tf.matmul(matrix1, matrix2)


In [17]:
product.numpy()

array([[19, 22],
       [43, 50]])

In [19]:
# tf supports all variable types
# default is tf.int32 and tf.float32
t1 = tf.Variable(32) # tensor variable

In [20]:
type(t1)

tensorflow.python.ops.resource_variable_ops.ResourceVariable

In [21]:
print(t1)
print(t1.dtype)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=32>
<dtype: 'int32'>


In [23]:
f1 = tf.Variable(89.)
f1

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=89.0>

In [25]:
f1.assign(98.)
f1

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=98.0>

In [26]:
# specifying dtype
f64 = tf.Variable(89, dtype=tf.float64)
f64.dtype

tf.float64

In [28]:
# The rank (dimensions) of a tensor
t2 = tf.Variable([[[0., 1., 2.], [3., 4., 5.] ], [[6., 7., 8.], [9., 10., 11.]]])
t2

<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=float32, numpy=
array([[[ 0.,  1.,  2.],
        [ 3.,  4.,  5.]],

       [[ 6.,  7.,  8.],
        [ 9., 10., 11.]]], dtype=float32)>

In [31]:
tf.rank(t2)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [35]:
tf.rank?

In [32]:
print(t2.shape)

(2, 2, 3)


In [33]:
t2[1,1,2].numpy()

11.0

In [29]:
country = tf.Variable('india', dtype=tf.string)
country

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'india'>

In [30]:
country.numpy()

b'india'

In [34]:
y = tf.ones((1,5))
print(y)

tf.Tensor([[1. 1. 1. 1. 1.]], shape=(1, 5), dtype=float32)


In [36]:
# find the size (total nb of elements) of a tensor
s = tf.size(input=t2).numpy()
s

12

In [37]:
# casting tensor to numpy variable
print(t2.numpy())

[[[ 0.  1.  2.]
  [ 3.  4.  5.]]

 [[ 6.  7.  8.]
  [ 9. 10. 11.]]]


In [38]:
# Specify an element of a tensor
print(t2[1,0,1].numpy())

7.0


In [39]:
x = tf.constant(4.0, dtype='float32')

In [40]:
print(tf.sqrt(x))

tf.Tensor(2.0, shape=(), dtype=float32)


In [41]:
x = tf.Variable(4.0)
print(tf.sqrt(x))

tf.Tensor(2.0, shape=(), dtype=float32)


In [42]:
print(tf.exp(x))

tf.Tensor(54.59815, shape=(), dtype=float32)


In [43]:
tf.pow(2,3)

<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [45]:
d = tf.range(1,10,2)
d.numpy()

array([1, 3, 5, 7, 9])

In [48]:
# reshape
k = tf.constant([1,2,3,4,5,6])
l = tf.reshape(k,[2,3])

In [49]:
l

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>